//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace NFe.Components.HMaringaPR {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="NfseServicesBinding", Namespace="https://nfse-ws.hom-ecity.maringa.pr.gov.br/v2.01")]
    public partial class NfseServicesService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback EnviarLoteRpsOperationCompleted;
        
        private System.Threading.SendOrPostCallback EnviarLoteDeducaoSincronoOperationCompleted;
        
        private System.Threading.SendOrPostCallback EnviarLoteRpsSincronoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GerarNfseOperationCompleted;
        
        private System.Threading.SendOrPostCallback CancelarNfseOperationCompleted;
        
        private System.Threading.SendOrPostCallback SubstituirNfseOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarLoteRpsOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarNfseRpsOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarNfseServicoPrestadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarNfseServicoTomadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarNfseFaixaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidarXmlOperationCompleted;
        
        private System.Threading.SendOrPostCallback TesteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public NfseServicesService() {
            this.Url = global::NFe.Components.Properties.Settings.Default.NFe_Components_HMaringaPR_NfseServicesService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event EnviarLoteRpsCompletedEventHandler EnviarLoteRpsCompleted;
        
        /// <remarks/>
        public event EnviarLoteDeducaoSincronoCompletedEventHandler EnviarLoteDeducaoSincronoCompleted;
        
        /// <remarks/>
        public event EnviarLoteRpsSincronoCompletedEventHandler EnviarLoteRpsSincronoCompleted;
        
        /// <remarks/>
        public event GerarNfseCompletedEventHandler GerarNfseCompleted;
        
        /// <remarks/>
        public event CancelarNfseCompletedEventHandler CancelarNfseCompleted;
        
        /// <remarks/>
        public event SubstituirNfseCompletedEventHandler SubstituirNfseCompleted;
        
        /// <remarks/>
        public event ConsultarLoteRpsCompletedEventHandler ConsultarLoteRpsCompleted;
        
        /// <remarks/>
        public event ConsultarNfseRpsCompletedEventHandler ConsultarNfseRpsCompleted;
        
        /// <remarks/>
        public event ConsultarNfseServicoPrestadoCompletedEventHandler ConsultarNfseServicoPrestadoCompleted;
        
        /// <remarks/>
        public event ConsultarNfseServicoTomadoCompletedEventHandler ConsultarNfseServicoTomadoCompleted;
        
        /// <remarks/>
        public event ConsultarNfseFaixaCompletedEventHandler ConsultarNfseFaixaCompleted;
        
        /// <remarks/>
        public event ValidarXmlCompletedEventHandler ValidarXmlCompleted;
        
        /// <remarks/>
        public event TesteCompletedEventHandler TesteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://nfse-ws.hom-ecity.maringa.pr.gov.br/v2.01#EnviarLoteRps", RequestNamespace="https://nfse-ws.hom-ecity.maringa.pr.gov.br/v2.01", ResponseNamespace="https://nfse-ws.hom-ecity.maringa.pr.gov.br/v2.01")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string EnviarLoteRps(string xml) {
            object[] results = this.Invoke("EnviarLoteRps", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EnviarLoteRpsAsync(string xml) {
            this.EnviarLoteRpsAsync(xml, null);
        }
        
        /// <remarks/>
        public void EnviarLoteRpsAsync(string xml, object userState) {
            if ((this.EnviarLoteRpsOperationCompleted == null)) {
                this.EnviarLoteRpsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnviarLoteRpsOperationCompleted);
            }
            this.InvokeAsync("EnviarLoteRps", new object[] {
                        xml}, this.EnviarLoteRpsOperationCompleted, userState);
        }
        
        private void OnEnviarLoteRpsOperationCompleted(object arg) {
            if ((this.EnviarLoteRpsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnviarLoteRpsCompleted(this, new EnviarLoteRpsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://nfse-ws.hom-ecity.maringa.pr.gov.br/v2.01#EnviarLoteDeducaoSincrono", RequestNamespace="https://nfse-ws.hom-ecity.maringa.pr.gov.br/v2.01", ResponseNamespace="https://nfse-ws.hom-ecity.maringa.pr.gov.br/v2.01")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string EnviarLoteDeducaoSincrono(string xml) {
            object[] results = this.Invoke("EnviarLoteDeducaoSincrono", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EnviarLoteDeducaoSincronoAsync(string xml) {
            this.EnviarLoteDeducaoSincronoAsync(xml, null);
        }
        
        /// <remarks/>
        public void EnviarLoteDeducaoSincronoAsync(string xml, object userState) {
            if ((this.EnviarLoteDeducaoSincronoOperationCompleted == null)) {
                this.EnviarLoteDeducaoSincronoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnviarLoteDeducaoSincronoOperationCompleted);
            }
            this.InvokeAsync("EnviarLoteDeducaoSincrono", new object[] {
                        xml}, this.EnviarLoteDeducaoSincronoOperationCompleted, userState);
        }
        
        private void OnEnviarLoteDeducaoSincronoOperationCompleted(object arg) {
            if ((this.EnviarLoteDeducaoSincronoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnviarLoteDeducaoSincronoCompleted(this, new EnviarLoteDeducaoSincronoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://nfse-ws.hom-ecity.maringa.pr.gov.br/v2.01#EnviarLoteRpsSincrono", RequestNamespace="https://nfse-ws.hom-ecity.maringa.pr.gov.br/v2.01", ResponseNamespace="https://nfse-ws.hom-ecity.maringa.pr.gov.br/v2.01")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string EnviarLoteRpsSincrono(string xml) {
            object[] results = this.Invoke("EnviarLoteRpsSincrono", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EnviarLoteRpsSincronoAsync(string xml) {
            this.EnviarLoteRpsSincronoAsync(xml, null);
        }
        
        /// <remarks/>
        public void EnviarLoteRpsSincronoAsync(string xml, object userState) {
            if ((this.EnviarLoteRpsSincronoOperationCompleted == null)) {
                this.EnviarLoteRpsSincronoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnviarLoteRpsSincronoOperationCompleted);
            }
            this.InvokeAsync("EnviarLoteRpsSincrono", new object[] {
                        xml}, this.EnviarLoteRpsSincronoOperationCompleted, userState);
        }
        
        private void OnEnviarLoteRpsSincronoOperationCompleted(object arg) {
            if ((this.EnviarLoteRpsSincronoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnviarLoteRpsSincronoCompleted(this, new EnviarLoteRpsSincronoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://nfse-ws.hom-ecity.maringa.pr.gov.br/v2.01#GerarNfse", RequestNamespace="https://nfse-ws.hom-ecity.maringa.pr.gov.br/v2.01", ResponseNamespace="https://nfse-ws.hom-ecity.maringa.pr.gov.br/v2.01")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string GerarNfse(string xml) {
            object[] results = this.Invoke("GerarNfse", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GerarNfseAsync(string xml) {
            this.GerarNfseAsync(xml, null);
        }
        
        /// <remarks/>
        public void GerarNfseAsync(string xml, object userState) {
            if ((this.GerarNfseOperationCompleted == null)) {
                this.GerarNfseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGerarNfseOperationCompleted);
            }
            this.InvokeAsync("GerarNfse", new object[] {
                        xml}, this.GerarNfseOperationCompleted, userState);
        }
        
        private void OnGerarNfseOperationCompleted(object arg) {
            if ((this.GerarNfseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GerarNfseCompleted(this, new GerarNfseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://nfse-ws.hom-ecity.maringa.pr.gov.br/v2.01#CancelarNfse", RequestNamespace="https://nfse-ws.hom-ecity.maringa.pr.gov.br/v2.01", ResponseNamespace="https://nfse-ws.hom-ecity.maringa.pr.gov.br/v2.01")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string CancelarNfse(string xml) {
            object[] results = this.Invoke("CancelarNfse", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CancelarNfseAsync(string xml) {
            this.CancelarNfseAsync(xml, null);
        }
        
        /// <remarks/>
        public void CancelarNfseAsync(string xml, object userState) {
            if ((this.CancelarNfseOperationCompleted == null)) {
                this.CancelarNfseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCancelarNfseOperationCompleted);
            }
            this.InvokeAsync("CancelarNfse", new object[] {
                        xml}, this.CancelarNfseOperationCompleted, userState);
        }
        
        private void OnCancelarNfseOperationCompleted(object arg) {
            if ((this.CancelarNfseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CancelarNfseCompleted(this, new CancelarNfseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://nfse-ws.hom-ecity.maringa.pr.gov.br/v2.01#SubstituirNfse", RequestNamespace="https://nfse-ws.hom-ecity.maringa.pr.gov.br/v2.01", ResponseNamespace="https://nfse-ws.hom-ecity.maringa.pr.gov.br/v2.01")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string SubstituirNfse(string xml) {
            object[] results = this.Invoke("SubstituirNfse", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SubstituirNfseAsync(string xml) {
            this.SubstituirNfseAsync(xml, null);
        }
        
        /// <remarks/>
        public void SubstituirNfseAsync(string xml, object userState) {
            if ((this.SubstituirNfseOperationCompleted == null)) {
                this.SubstituirNfseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSubstituirNfseOperationCompleted);
            }
            this.InvokeAsync("SubstituirNfse", new object[] {
                        xml}, this.SubstituirNfseOperationCompleted, userState);
        }
        
        private void OnSubstituirNfseOperationCompleted(object arg) {
            if ((this.SubstituirNfseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SubstituirNfseCompleted(this, new SubstituirNfseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://nfse-ws.hom-ecity.maringa.pr.gov.br/v2.01#ConsultarLoteRps", RequestNamespace="https://nfse-ws.hom-ecity.maringa.pr.gov.br/v2.01", ResponseNamespace="https://nfse-ws.hom-ecity.maringa.pr.gov.br/v2.01")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string ConsultarLoteRps(string xml) {
            object[] results = this.Invoke("ConsultarLoteRps", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarLoteRpsAsync(string xml) {
            this.ConsultarLoteRpsAsync(xml, null);
        }
        
        /// <remarks/>
        public void ConsultarLoteRpsAsync(string xml, object userState) {
            if ((this.ConsultarLoteRpsOperationCompleted == null)) {
                this.ConsultarLoteRpsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarLoteRpsOperationCompleted);
            }
            this.InvokeAsync("ConsultarLoteRps", new object[] {
                        xml}, this.ConsultarLoteRpsOperationCompleted, userState);
        }
        
        private void OnConsultarLoteRpsOperationCompleted(object arg) {
            if ((this.ConsultarLoteRpsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarLoteRpsCompleted(this, new ConsultarLoteRpsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://nfse-ws.hom-ecity.maringa.pr.gov.br/v2.01#ConsultarNfseRps", RequestNamespace="https://nfse-ws.hom-ecity.maringa.pr.gov.br/v2.01", ResponseNamespace="https://nfse-ws.hom-ecity.maringa.pr.gov.br/v2.01")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string ConsultarNfseRps(string xml) {
            object[] results = this.Invoke("ConsultarNfseRps", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarNfseRpsAsync(string xml) {
            this.ConsultarNfseRpsAsync(xml, null);
        }
        
        /// <remarks/>
        public void ConsultarNfseRpsAsync(string xml, object userState) {
            if ((this.ConsultarNfseRpsOperationCompleted == null)) {
                this.ConsultarNfseRpsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarNfseRpsOperationCompleted);
            }
            this.InvokeAsync("ConsultarNfseRps", new object[] {
                        xml}, this.ConsultarNfseRpsOperationCompleted, userState);
        }
        
        private void OnConsultarNfseRpsOperationCompleted(object arg) {
            if ((this.ConsultarNfseRpsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarNfseRpsCompleted(this, new ConsultarNfseRpsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://nfse-ws.hom-ecity.maringa.pr.gov.br/v2.01#ConsultarNfseServicoPrestado", RequestNamespace="https://nfse-ws.hom-ecity.maringa.pr.gov.br/v2.01", ResponseNamespace="https://nfse-ws.hom-ecity.maringa.pr.gov.br/v2.01")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string ConsultarNfseServicoPrestado(string xml) {
            object[] results = this.Invoke("ConsultarNfseServicoPrestado", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarNfseServicoPrestadoAsync(string xml) {
            this.ConsultarNfseServicoPrestadoAsync(xml, null);
        }
        
        /// <remarks/>
        public void ConsultarNfseServicoPrestadoAsync(string xml, object userState) {
            if ((this.ConsultarNfseServicoPrestadoOperationCompleted == null)) {
                this.ConsultarNfseServicoPrestadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarNfseServicoPrestadoOperationCompleted);
            }
            this.InvokeAsync("ConsultarNfseServicoPrestado", new object[] {
                        xml}, this.ConsultarNfseServicoPrestadoOperationCompleted, userState);
        }
        
        private void OnConsultarNfseServicoPrestadoOperationCompleted(object arg) {
            if ((this.ConsultarNfseServicoPrestadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarNfseServicoPrestadoCompleted(this, new ConsultarNfseServicoPrestadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://nfse-ws.hom-ecity.maringa.pr.gov.br/v2.01#ConsultarNfseServicoTomado", RequestNamespace="https://nfse-ws.hom-ecity.maringa.pr.gov.br/v2.01", ResponseNamespace="https://nfse-ws.hom-ecity.maringa.pr.gov.br/v2.01")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string ConsultarNfseServicoTomado(string xml) {
            object[] results = this.Invoke("ConsultarNfseServicoTomado", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarNfseServicoTomadoAsync(string xml) {
            this.ConsultarNfseServicoTomadoAsync(xml, null);
        }
        
        /// <remarks/>
        public void ConsultarNfseServicoTomadoAsync(string xml, object userState) {
            if ((this.ConsultarNfseServicoTomadoOperationCompleted == null)) {
                this.ConsultarNfseServicoTomadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarNfseServicoTomadoOperationCompleted);
            }
            this.InvokeAsync("ConsultarNfseServicoTomado", new object[] {
                        xml}, this.ConsultarNfseServicoTomadoOperationCompleted, userState);
        }
        
        private void OnConsultarNfseServicoTomadoOperationCompleted(object arg) {
            if ((this.ConsultarNfseServicoTomadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarNfseServicoTomadoCompleted(this, new ConsultarNfseServicoTomadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://nfse-ws.hom-ecity.maringa.pr.gov.br/v2.01#ConsultarNfseFaixa", RequestNamespace="https://nfse-ws.hom-ecity.maringa.pr.gov.br/v2.01", ResponseNamespace="https://nfse-ws.hom-ecity.maringa.pr.gov.br/v2.01")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string ConsultarNfseFaixa(string xml) {
            object[] results = this.Invoke("ConsultarNfseFaixa", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarNfseFaixaAsync(string xml) {
            this.ConsultarNfseFaixaAsync(xml, null);
        }
        
        /// <remarks/>
        public void ConsultarNfseFaixaAsync(string xml, object userState) {
            if ((this.ConsultarNfseFaixaOperationCompleted == null)) {
                this.ConsultarNfseFaixaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarNfseFaixaOperationCompleted);
            }
            this.InvokeAsync("ConsultarNfseFaixa", new object[] {
                        xml}, this.ConsultarNfseFaixaOperationCompleted, userState);
        }
        
        private void OnConsultarNfseFaixaOperationCompleted(object arg) {
            if ((this.ConsultarNfseFaixaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarNfseFaixaCompleted(this, new ConsultarNfseFaixaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://nfse-ws.hom-ecity.maringa.pr.gov.br/v2.01#ValidarXml", RequestNamespace="https://nfse-ws.hom-ecity.maringa.pr.gov.br/v2.01", ResponseNamespace="https://nfse-ws.hom-ecity.maringa.pr.gov.br/v2.01")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public object ValidarXml(string xml) {
            object[] results = this.Invoke("ValidarXml", new object[] {
                        xml});
            return ((object)(results[0]));
        }
        
        /// <remarks/>
        public void ValidarXmlAsync(string xml) {
            this.ValidarXmlAsync(xml, null);
        }
        
        /// <remarks/>
        public void ValidarXmlAsync(string xml, object userState) {
            if ((this.ValidarXmlOperationCompleted == null)) {
                this.ValidarXmlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidarXmlOperationCompleted);
            }
            this.InvokeAsync("ValidarXml", new object[] {
                        xml}, this.ValidarXmlOperationCompleted, userState);
        }
        
        private void OnValidarXmlOperationCompleted(object arg) {
            if ((this.ValidarXmlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidarXmlCompleted(this, new ValidarXmlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://nfse-ws.hom-ecity.maringa.pr.gov.br/v2.01#Teste", RequestNamespace="https://nfse-ws.hom-ecity.maringa.pr.gov.br/v2.01", ResponseNamespace="https://nfse-ws.hom-ecity.maringa.pr.gov.br/v2.01")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public object Teste(string xml) {
            object[] results = this.Invoke("Teste", new object[] {
                        xml});
            return ((object)(results[0]));
        }
        
        /// <remarks/>
        public void TesteAsync(string xml) {
            this.TesteAsync(xml, null);
        }
        
        /// <remarks/>
        public void TesteAsync(string xml, object userState) {
            if ((this.TesteOperationCompleted == null)) {
                this.TesteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTesteOperationCompleted);
            }
            this.InvokeAsync("Teste", new object[] {
                        xml}, this.TesteOperationCompleted, userState);
        }
        
        private void OnTesteOperationCompleted(object arg) {
            if ((this.TesteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TesteCompleted(this, new TesteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void EnviarLoteRpsCompletedEventHandler(object sender, EnviarLoteRpsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnviarLoteRpsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EnviarLoteRpsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void EnviarLoteDeducaoSincronoCompletedEventHandler(object sender, EnviarLoteDeducaoSincronoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnviarLoteDeducaoSincronoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EnviarLoteDeducaoSincronoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void EnviarLoteRpsSincronoCompletedEventHandler(object sender, EnviarLoteRpsSincronoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnviarLoteRpsSincronoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EnviarLoteRpsSincronoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GerarNfseCompletedEventHandler(object sender, GerarNfseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GerarNfseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GerarNfseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CancelarNfseCompletedEventHandler(object sender, CancelarNfseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CancelarNfseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CancelarNfseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SubstituirNfseCompletedEventHandler(object sender, SubstituirNfseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SubstituirNfseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SubstituirNfseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ConsultarLoteRpsCompletedEventHandler(object sender, ConsultarLoteRpsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarLoteRpsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarLoteRpsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ConsultarNfseRpsCompletedEventHandler(object sender, ConsultarNfseRpsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarNfseRpsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarNfseRpsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ConsultarNfseServicoPrestadoCompletedEventHandler(object sender, ConsultarNfseServicoPrestadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarNfseServicoPrestadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarNfseServicoPrestadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ConsultarNfseServicoTomadoCompletedEventHandler(object sender, ConsultarNfseServicoTomadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarNfseServicoTomadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarNfseServicoTomadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ConsultarNfseFaixaCompletedEventHandler(object sender, ConsultarNfseFaixaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarNfseFaixaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarNfseFaixaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ValidarXmlCompletedEventHandler(object sender, ValidarXmlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidarXmlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidarXmlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void TesteCompletedEventHandler(object sender, TesteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TesteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TesteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591